// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product_categories

import (
	"gorm.io/gorm"
	"iswift-go-project/internal/product_category/delivery/http"
	product_category2 "iswift-go-project/internal/product_category/repository"
	product_category3 "iswift-go-project/internal/product_category/usecase"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *product_category.ProductCategoryHandler {
	productcategoryRepository := product_category2.NewProductCategoryRepository(db)
	productCategoryUseCase := product_category3.NewProductCategoryUseCase(productcategoryRepository)
	productCategoryHandler := product_category.NewProductCategoryHandler(productCategoryUseCase)
	return productCategoryHandler
}
