// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"gorm.io/gorm"
	"iswift-go-project/internal/product/delivery/http"
	product2 "iswift-go-project/internal/product/repository"
	"iswift-go-project/internal/product/usecase"
	"iswift-go-project/pkg/fileupload/cloudinary"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *product.ProductHanlder {
	productRepository := product2.NewProductRepository(db)
	fileUpload := fileupload.NewFileUpload()
	productUseCase := products.NewProductUsecase(productRepository, fileUpload)
	productHanlder := product.NewProductHandler(productUseCase)
	return productHanlder
}
