// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package register

import (
	"gorm.io/gorm"
	"iswift-go-project/internal/register/delivery/http"
	register2 "iswift-go-project/internal/register/usecase"
	"iswift-go-project/internal/user/repository"
	user2 "iswift-go-project/internal/user/usecase"
	"iswift-go-project/pkg/mail/sendgrid"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *register.RegisterHandler {
	userRepository := user.NewUserRepository(db)
	userUseCase := user2.NewUserUseCase(userRepository)
	mail := sendgrid.NewMail()
	registerUseCase := register2.NewRegisterUseCase(userUseCase, mail)
	registerHandler := register.NewRegisterHandler(registerUseCase)
	return registerHandler
}
