// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package profile

import (
	"gorm.io/gorm"
	"iswift-go-project/internal/profile/delivery/http"
	profile2 "iswift-go-project/internal/profile/usecase"
	"iswift-go-project/internal/user/repository"
	user2 "iswift-go-project/internal/user/usecase"
)

// Injectors from wire.go:

func InitializedService(db *gorm.DB) *profile.ProfileHandler {
	userRepository := user.NewUserRepository(db)
	userUseCase := user2.NewUserUseCase(userRepository)
	profileUseCase := profile2.NewProfileUseCase(userUseCase)
	profileHandler := profile.NewProfileHanlder(profileUseCase)
	return profileHandler
}
